Proto = {
	CREATE_BATTLE_FIELD:"1",
	CREATE_BATTLE_FIELD_DONE:"2",
	REQUEST_BATTLE_FIELD_LIST:"3",
	RESPONSE_BATTLE_FIELD_LIST:"4",
	JOIN_BATTLE_FIELD:"5",
	NEW_JOIN:"6",
	PLAYER_JOIN:"7",
	SYNC_PLAYER_LIST:"8",
	REQUEST_FIRE:"9",
	FIRE:"10"
};
if (module) module.exports = Proto;