Proto = {
	CREATE_BATTLE_FIELD:"1",
	CREATE_BATTLE_FIELD_DONE:"2",
	REQUEST_BATTLE_FIELD_LIST:"3",
	RESPONSE_BATTLE_FIELD_LIST:"4",
	JOIN_BATTLE_FIELD:"5",
	NEW_JOIN:"6",
	PLAYER_JOIN:"7",
	SYNC_PLAYER_LIST:"8",
	REQUEST_SYNC_TIME:"9",
	RESPONSE_SYNC_TIME:"10",
	REQUEST_MOVE:"11",
	FIRE:"12",
	UPLOAD_ACTION:"13",
	UPLOAD_KINEMATICS:"14",
	SYNC_KINEMATICS:"15"
};
if (module) module.exports = Proto;